[build]
  command = "pnpm install && pnpm run build"
  publish = "dist/client"
  functions = "dist/server"
[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200